### ISSUE TITLE
Error when trying to train CLAP

### ISSUE THREAD

**Issue by Saltb0xApps** [zhvng/open-musiclm#2]
$ python train_clap_rvq.py 

```
found ignored file, skipping
found ignored file, skipping
found ignored file, skipping
found ignored file, skipping
found ignored file, skipping
found ignored file, skipping
training with dataset of 7594 samples and validating with randomly splitted 400 samples
Traceback (most recent call last):
  File "/Users/akhiltolani/Desktop/open-musiclm-main/scripts/train_clap_rvq.py", line 37, in <module>
    trainer.train()
  File "/Users/akhiltolani/Desktop/open-musiclm-main/scripts/../open_musiclm/trainer.py", line 507, in train
    logs = self.train_step()
  File "/Users/akhiltolani/Desktop/open-musiclm-main/scripts/../open_musiclm/trainer.py", line 473, in train_step
    raw_wave_for_clap = next(self.dl_iter)[0]
IndexError: tuple index out of range
```

**Comment by zhvng** [comment]
Hey Akhil, thanks for testing out my code! I'm not sure what's happening here but it's working for me. What is your batch size?

**Comment by Saltb0xApps** [comment]
@zhvng  Yes, I'm trying to run train_clap_rvq.py on the fma_small dataset. The batch size and all the other parameters are the same as the default values.

```
device = 'cuda' if torch.cuda.is_available() else 'cpu'

clap_checkpoint = "./checkpoints/clap-laion-audioset-fusion.pt"
# rvq_checkpoint = './results/semantic/semantic.conditioner_rvq.20000.pt'
with disable_print():
    clap = create_clap_quantized(device=device, learn_rvq=True, checkpoint_path=clap_checkpoint, rvq_checkpoint_path=None).to(device)

corrupted_files = ['fma_small/098/098565.mp3',
                   'fma_small/098/098567.mp3',
                   'fma_small/098/098569.mp3',
                   'fma_small/099/099134.mp3',
                   'fma_small/108/108925.mp3',
                   'fma_small/133/133297.mp3']
trainer = ClapRVQTrainer(
    num_train_steps=1000, 
    batch_size=32, 
    audio_conditioner=clap, 
    folder='../audiolm-train/audio', 
    results_folder='./results/clap_rvq',
    ignore_files=corrupted_files,
    save_model_every=100,
    save_results_every=50
).to(device)

trainer.train()
```
../audiolm-train/audio contains the unzipped fma_small dataset

**Comment by Saltb0xApps** [comment]
when I try to `print(nex(self.dl_iter))`, the result is an empty tuple `()` which is why the trainer is failing. Any ideas why this could be happening?

**Comment by Saltb0xApps** [comment]
Note - the same issue happens when I try to train the Hubert model too
```
audio_folder = './data/fma_large'

print('loading hubert...')
hubert_kmeans = get_hubert_kmeans(model_name='m-a-p/MERT-v0', kmeans_path=None)
trainer = HfHubertKmeansTrainer(
    feature_extraction_num_steps=100,
    feature_extraction_batch_size=64,
    data_max_length=16000*8,
    hubert_kmeans=hubert_kmeans,
    folder=audio_folder,
    results_folder='./results/hubert_kmeans',
).to(device)

trainer.train()
```
Error -
```
(base) akhiltolani@Akhils-MacBook-Pro-2 scripts % python train_hubert_kmeans.py
loading hubert...
training on 6400 out of 106574 samples
step 1: extracting features. must wait for this to complete before training kmeans.
0 / 100 steps
Traceback (most recent call last):
  File "/Users/akhiltolani/Desktop/open-musiclm-main 2/scripts/train_hubert_kmeans.py", line 29, in <module>
    trainer.train()
  File "/Users/akhiltolani/Desktop/open-musiclm-main 2/scripts/../open_musiclm/trainer.py", line 591, in train
    features.append(self.extract_hubert_features())
  File "/Users/akhiltolani/Desktop/open-musiclm-main 2/scripts/../open_musiclm/trainer.py", line 575, in extract_hubert_features
    raw_wave = next(self.dl_iter)[0]
IndexError: tuple index out of range
```

**Comment by Saltb0xApps** [comment]
The root cause of my issues was using the incorrect version of torch!
