### ISSUE TITLE
can't train the clap

### ISSUE THREAD

**Issue by vivagwb** [zhvng/open-musiclm#21]
(open-musiclm) G:\Learn\AmateurLearning\AI\Practice\open-musiclm-main>python ./scripts/train_clap_rvq.py --results_folder ./results/clap_rvq --model_config ./configs/model/musiclm_small.json --training_config ./configs/training/train_musiclm_fma.json
loading clap...
Some weights of the model checkpoint at roberta-base were not used when initializing RobertaModel: ['lm_head.decoder.weight', 'lm_head.dense.weight', 'lm_head.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.dense.bias']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
F:\Miniconda\envs\open-musiclm\Lib\site-packages\torchaudio\transforms\_transforms.py:611: UserWarning: Argument 'onesided' has been deprecated and has no influence on the behavior of this module.
  warnings.warn(
F:\Miniconda\envs\open-musiclm\Lib\site-packages\accelerate\accelerator.py:258: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
F:\Miniconda\envs\open-musiclm\Lib\site-packages\accelerate\accelerator.py:375: UserWarning: `log_with=tensorboard` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
Traceback (most recent call last):
  File "G:\Learn\AmateurLearning\AI\Practice\open-musiclm-main\scripts\train_clap_rvq.py", line 33, in <module>
    trainer = create_clap_rvq_trainer_from_config(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Learn\AmateurLearning\AI\Practice\open-musiclm-main\scripts\..\open_musiclm\config.py", line 317, in create_clap_rvq_trainer_from_config
    trainer = ClapRVQTrainer(
              ^^^^^^^^^^^^^^^
  File "G:\Learn\AmateurLearning\AI\Practice\open-musiclm-main\scripts\..\open_musiclm\trainer.py", line 606, in __init__
    self.ds = SoundDataset(
              ^^^^^^^^^^^^^
  File "G:\Learn\AmateurLearning\AI\Practice\open-musiclm-main\scripts\..\open_musiclm\data.py", line 80, in __init__
    assert path.exists(), 'folder does not exist'
AssertionError: folder does not exist @zhvng @jlalmes

**Comment by MichaelALong** [comment]
This error is because it cannot find the training data. The training_config parameter should be the config file which specifies the data directory. To download the fma data, use the script download_fma_large.sh. There is also a small (7GB) FMA version which you can manually download instead.

**Comment by fahnub** [comment]
Thanks for this @MichaelALong

**Comment by baardev** [comment]
just create the folder `data/fma_large` (or whatever has been defined as "folder" in `configs/training/train_musiclm_fma.json`) and you will move past that error to the next error, "no files exists".  Again, this mystery is solved by copying your 'mp3', 'wav', or 'flac' files to `data/fma_large'.

Suggestions to dev.  instead of 'folder does not exist" and "no files exist", maybe say "folder 'data/fma_large' does not exist" and "No Wav, flac, MP3 files found in 'data/fma_large'"
